# This file is used to define multiple containers that work together as part of this application

services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend