# This file is used to define multiple containers that work together as part of this application

version: "3"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "3000:3000"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3001:3001"
